var body = document.querySelector('body')
var header = document.createElement('header')
header.setAttribute('class','navbar')

var div1 = document.createElement('div')
var a1 = document.createElement('a')
a1.setAttribute('href',"/tds-web-alt/index.html")
a1.setAttribute('class','menu')
a1.appendChild(document.createTextNode('Accueil'))
div1.appendChild(a1)

var div2 = document.createElement('div')
var a2 = document.createElement('a')
a2.setAttribute('href',"")
a2.setAttribute('class','menu')
a2.appendChild(document.createTextNode('A propos'))
div2.appendChild(a2)

var div3 = document.createElement('div')
var a3 = document.createElement('a')
a3.setAttribute('href',"/tds-web-alt/pages/competences/competences.html")
a3.setAttribute('class','menu')
a3.appendChild(document.createTextNode('Compétences'))
div3.appendChild(a3)

var div4 = document.createElement('div')
var a4 = document.createElement('a')
a4.setAttribute('href',"")
a4.setAttribute('class','menu')
a4.appendChild(document.createTextNode('Experiences'))
div4.appendChild(a4)

var div5 = document.createElement('div')
var a5 = document.createElement('a')
a5.setAttribute('href',"")
a5.setAttribute('class','menu')
a5.appendChild(document.createTextNode('Formations'))
div5.appendChild(a5)

var div6 = document.createElement('div')
var a6 = document.createElement('a')
a6.setAttribute('href',"")
a6.setAttribute('class','contact')
a6.appendChild(document.createTextNode('Conctact'))
div6.appendChild(a6)

header.appendChild(div1)
header.appendChild(div2)
header.appendChild(div3)
header.appendChild(div4)
header.appendChild(div5)
header.appendChild(div6)

body.insertBefore(header,body.firstChild)